# Generated by Django 3.2.12 on 2022-02-20 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('state', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تلفن')),
                ('birth_year', models.CharField(max_length=50, verbose_name='سال تولد')),
                ('gender', models.CharField(choices=[('آقا', 'آقا'), ('خانم', 'خانم')], max_length=50, verbose_name='جنسیت')),
                ('about_me', models.TextField(verbose_name='متن درباره من')),
                ('experience', models.TextField(verbose_name='سوابق شغلی')),
                ('education', models.TextField(verbose_name='سوابق تحصیلی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
