# Generated by Django 3.2.12 on 2022-02-13 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شرکت یا ارگان')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('person_number_from', models.IntegerField(blank=True, null=True, verbose_name='تعداد افراد مورد نیاز از')),
                ('person_number_until', models.IntegerField(blank=True, null=True, verbose_name='تعداد افراد مورد نیاز تا')),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='سایت یا وبلاگ')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع آگهی')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('job_type', models.CharField(blank=True, choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('کارآموزی', 'کارآموزی'), ('دورکاری', 'دورکاری')], max_length=50, null=True, verbose_name='نوع قرارداد')),
                ('experience', models.CharField(blank=True, choices=[('مهم نیست', 'مهم نیست'), ('کمتر از سه سال', 'کمتر از سه سال'), ('سه تا شش سال', 'سه تا شش سال'), ('بیشتر از شش سال', 'بیشتر از شش سال')], max_length=50, null=True, verbose_name='سابقه کار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کار')),
                ('company_introduction', models.TextField(blank=True, null=True, verbose_name='معرفی شرکت')),
                ('gender', models.CharField(blank=True, choices=[('مهم نیست', 'مهم نیست'), ('آقا', 'آقا'), ('خانم', 'خانم')], max_length=50, null=True, verbose_name='جنسیت')),
                ('published', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام مهارت')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='job.Skill', verbose_name='مهارت های مورد نیاز'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='work_category',
            field=models.ManyToManyField(blank=True, null=True, to='job.WorkCategory', verbose_name='دسته بندی شغلی'),
        ),
    ]
